import Head from "next/head";
import styles from "../styles/Home.module.css";

import Banner from "../components/banner/banner";
import NavBar from "../components/nav/navbar";

import SectionCards from "../components/card/section-cards";

import {
  getVideos,
  getPopularVideos,
  getWatchItAgainVideos,
} from "../lib/videos";

import useRedirectUser from "../utils/redirectUser";

export async function getServerSideProps(context) {
  const { token, userId } = await useRedirectUser(context);

  if (!token) {
    return {
      props: {},
      redirect: {
        destination: "/login", // using next.js middleware instead of this
        permanent: false,
      },
    };
  }

  const watchAgainVideos = await getWatchItAgainVideos(userId, token);
  const disneyVideos = await getVideos("disneyTrailer");
  const bestAnime = await getVideos("bestAnime");
  const marvelMovies = await getVideos("marvelMovies");
  const Popular = await getPopularVideos();

  // ssr
  return {
    props: {
      disneyVideos,
      Popular,
      bestAnime,
      marvelMovies,
      watchAgainVideos,
    },
  };
}

export default function Home({
  disneyVideos,
  Popular,
  bestAnime,
  marvelMovies,
  watchAgainVideos,
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nel-Prix</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <div className={styles.main}>
        <NavBar username="JLML" />
        <Banner
          videoId={"jiJu4K2jems"}
          title="Demon Slayer"
          subtitle="Let the hunting begin..."
          imgUrl={
            "https://www.cheatsheet.com/wp-content/uploads/2021/11/Demon-Slayer-Entertainment-District.jpeg"
          }
        />
        <div className={styles.sectionWrapper}>
          <SectionCards title="Disney" videos={disneyVideos} size="large" />
          <SectionCards
            title="watch it again"
            videos={watchAgainVideos}
            size="small"
          />
          <SectionCards title="Best Anime" videos={bestAnime} size="small" />
          <SectionCards
            title="Marvel Movies"
            videos={marvelMovies}
            size="medium"
          />
          <SectionCards title="popular" videos={Popular} size="small" />
        </div>
      </div>
    </div>
  );
}
